{% set name = "Pandemy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 364e768ddaa87b47eb490b584f7948a70b2d2b897f5d3a52e839f6b0c03e43a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - pandas >=1.2.0
    - sqlalchemy >=1.4.0
  run_constrained:
    - cx_oracle >=7

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pandemy
  commands:
    - pip check

about:
  home: https://github.com/antonlydell/Pandemy
  summary: 'A wrapper around pandas and SQLAlchemy to provide an easy interface for DataFrames and databases.'
  description: |
    Pandemy is a wrapper around pandas and SQLAlchemy to provide an easy class based interface for working with DataFrames and databases.
    This package is for those who enjoy working with pandas and SQL but do not want to learn all "bells and whistles" of SQLAlchemy.
    Use your existing SQL knowledge and provide text based SQL statements to load DataFrames from and write DataFrames to databases.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pandemy.readthedocs.io
  dev_url: https://github.com/antonlydell/Pandemy

extra:
  recipe-maintainers:
    - antonlydell
